lanche = ('Hambúguer','Suco', 'Pizza', 'Pudim','Batata Frita')
print(lanche)
print(lanche[1])
print(lanche[-2])
print(lanche[:2])
print(lanche[-2:])
print(lanche[::2])
print(lanche[::-1])
for comida in lanche:
    print(f'Eu vou comer {comida}!')
print('Comi pra caramba!')
print(len(lanche))
for cont in range(0, len(lanche)):
    print(lanche[cont])
for posicao,comida in enumerate(lanche):
    print(f'Eu vou comer {comida} na posição {posicao}!')

print(sorted(lanche))
print(lanche)
a = (2,5,4)
b = (5,8,1,2)
c = a + b
print(c)
print(c.count(5))
print(c.count(8))
print(c.count(2))
print(c.index(5))
print(c.index(5,1))
print(c.index(5,2))
pessoa = ('Gustavo',39,'M',99.88)
print(pessoa)
del(pessoa)
input('\n\033[1:34mDigite "sair" para sair: \033[m')