texto = str(input('Digite um texto pequeno todo em letras maiúsculas: '))
texto = texto.capitalize()
print('O texto digitado corretamente é fica assim: {}'.format(texto))
nome = str(input('Digite seu nome completo todo em letras minúsculas ou maiúsculas: '))
nome = nome.title()
print('Seu nome digitado corretamente é: {}!'.format(nome))
lista = str(input('Digite o nome de três frutas: '))
lista = lista.split()
print('A lista que você digitou é dada como: {}'.format(lista))
print('Sua lista é: {}!'.format(', '.join(lista)))
input('Digite "sair" para sair: ')