import random
nome = str(input('Digite seu nome completo: '))
nome1 = str(input('Digite uma parte do seu nome: '))
posicao = nome.find(nome1)
print('o seu nome é "{}" e "{}" está na posição {}!'.format(nome,nome1,posicao))
dividido = nome.split()
print('O seu nome dividido é {}!'.format(dividido))
print('A segunda parte do seu nome é "{}"!'.format(dividido[1]))
print('A terceira letra da primeira parte do seu nome é: "{}"!'.format(dividido[0][2]))
random.shuffle(dividido)
nome7 = (dividido[0]+' '+dividido[1]+' '+dividido[2]+' '+dividido[3])
print('Seu nome inteiro bagunçado é "{}" e seu nome inteiro correto é "{}"!'.format(nome7,nome))
print('Seu nome bagunçado é "{}", e seu nome escrito corretamente é "{}"!'.format(dividido,nome))
input('Digite "sair" para sair: ')